version: 3.6.{build}
os: Visual Studio 2015
clone_depth: 2
configuration: Release

#environment:
#  VERSION_SUFFIX: -preview

init:
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="-pre" }

assembly_info:
  patch: true
  file: src\GlobalAssemblyInfo.cs
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}$(VERSION_SUFFIX) $(GIT_HASH)"

before_build:
  - ps: >-
      Get-ChildItem -Path .\ -Filter project.json -Recurse -Name |
      ForEach {
          $content = Get-Content "$_"
          $content = $content.Replace("99.99.99-dev", "$($env:APPVEYOR_BUILD_VERSION)$($env:VERSION_SUFFIX)")
          Set-Content "$_" $content -Encoding UTF8
      }
  - appveyor-retry nuget restore -verbosity quiet
  - dotnet restore -v Minimal

build_script:
  - ps: .\tools\Build.ps1

test_script:
  - dotnet test src\Exceptionless.Tests\

after_test:
  - ps: .\tools\Package.ps1

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      branch: master
      appveyor_repo_tag: true
    
notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    channel: '#notifications'