version: 4.3.{build}
os: Visual Studio 2017
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="pre" }
  - ps: 'Write-Output "Version: $($env:APPVEYOR_BUILD_VERSION)-$($env:VERSION_SUFFIX)"'

assembly_info:
  patch: true
  file: src\GlobalAssemblyInfo.cs
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}$(VERSION_SUFFIX) $(GIT_HASH)"

install:
  - ps: .\build\DisplayEnvironmentInfo.ps1

before_build:
  - ps: .\build\Set-BuildVersion -Version $env:APPVEYOR_BUILD_VERSION -Suffix $env:VERSION_SUFFIX
  - appveyor-retry dotnet restore -v Minimal
  - ps: Get-ChildItem -Path .\src -Recurse -Include @("*.Signed", "*Portable") | ForEach-Object  { & appveyor-retry dotnet restore $_ -v Minimal }

build_script:
  - ps: .\build\Build.ps1
  - dotnet build test\Exceptionless.Tests -c Release
  - dotnet build test\Exceptionless.MessagePack.Tests -c Release

#test_script:
#  - dotnet test test\Exceptionless.Tests\

after_test:
  - ps: .\build\Package.ps1

artifacts:
  - path: artifacts\*.nupkg
    name: ReleaseArtifacts

deploy:
  - provider: Environment
    name: MyGet
  - provider: Environment
    name: NuGet
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: GniMpFE62HprSyQNQoej/fBOAdbQe8EMWAMMNXX0s2JxeNePjemiO1bCf4eYweE4p70mm0sCwMjeEP/Ps9aTMA==
    channel: '#notifications'
