name: Build OSX
on: [push, pull_request]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET Core 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      shell: bash
      run: |
        dotnet tool install --global minver-cli --version 6.0.0
        version=$(minver --tag-prefix v)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release Exceptionless.Net.NonWindows.slnx
    - name: Run Tests
      run: dotnet test --configuration Release --no-build Exceptionless.Net.NonWindows.slnx
